### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Borber** [Absolucy/tracing-oslog#15]
```
❯ RUST_BACKTRACE=full cargo build --target aarch64-apple-ios-sim --release
```

```
error: failed to run custom build command for `tracing-oslog v0.2.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/x/code/genmeta/gateway_new/gateway-sdk/target/release/build/tracing-oslog-e419f09405b95e6c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-apple-ios-sim
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_apple_ios_sim
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  error: version 'sim' in target triple 'arm64-apple-ios-sim' is invalid
  wrapper.h:1:10: fatal error: 'os/log.h' file not found

  thread 'main' panicked at /Users/x/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tracing-oslog-0.2.0/build.rs:38:10:
  Unable to generate bindings: ClangDiagnostic("error: version 'sim' in target triple 'arm64-apple-ios-sim' is invalid\nwrapper.h:1:10: fatal error: 'os/log.h' file not found\n")
  stack backtrace:
     0:        0x100cf46ac - __mh_execute_header
     1:        0x100d12924 - __mh_execute_header
     2:        0x100cf0f44 - __mh_execute_header
     3:        0x100cf4560 - __mh_execute_header
     4:        0x100cf5a28 - __mh_execute_header
     5:        0x100cf5874 - __mh_execute_header
     6:        0x100cf6410 - __mh_execute_header
     7:        0x100cf6134 - __mh_execute_header
     8:        0x100cf4b5c - __mh_execute_header
     9:        0x100cf5ddc - __mh_execute_header
    10:        0x100d29460 - __mh_execute_header
    11:        0x100d29750 - __mh_execute_header
    12:        0x1007c1274 - __mh_execute_header
    13:        0x1007c2b50 - __mh_execute_header
    14:        0x1007c0e74 - __mh_execute_header
    15:        0x1007c0e10 - __mh_execute_header
    16:        0x1007c0df4 - __mh_execute_header
    17:        0x100cecc74 - __mh_execute_header
    18:        0x1007c0dd8 - __mh_execute_header
    19:        0x1007c2e84 - __mh_execute_header
```

**Comment by Iskander508** [comment]
We ran into the same error after upgrading XCode to 16.3 on our CI machine.
After downgrading back to XCode 16.2 the build succeeds again.

**Comment by simlay** [comment]
Mads has a PR to fix this #12. If you run into it elsewhere, https://github.com/rust-lang/rust-bindgen/pull/3182 is kinda the root issue. Relevant: https://github.com/RustAudio/coreaudio-sys/pull/112

**Comment by extrawurst** [comment]
made it an explicit issue: https://github.com/rust-lang/rust-bindgen/issues/3199
